export const FETCH_START_AUTH = 'FETCH_START_AUTH';
export const FETCH_SUCCESS_AUTH = 'FETCH_SUCCESS_AUTH';
export const FETCH_FAILURE_AUTH = 'FETCH_FAILURE_AUTH';
export const CLEAR_ERROR_AUTH = 'CLEAR_ERROR_AUTH';
export const RESET_ERRORS_AUTH = 'RESET_ERRORS_AUTH';
